# title: Shivam Mishra
# logo: /assets/img/profile.jpg
# description: Hello there
# show_downloads: true
# theme: cayman
#jekyll-theme-minimal

title: Shivam Mishra
description: "A professional portfolio showcasing data science projects and skills."
logo: /assets/img/shimish_profile_image.png
show_downloads: true
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown

#google_analytics: UA-XXXXXXXX-X

# Social media settings
social:
  github: "https://github.com/shivam0296"
  linkedin: "https://www.linkedin.com/in/shivam-mishra0296/"

# header_pages:
#   - index.md
#   - projects.md
#   - about.md
#   - contact.md

author:
  name: "Shivam Mishra"
  email: "mishras0297@gmail.com"
  
show_excerpts: true
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

